apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: converter-namespace
  name: converter-api-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
