apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: converter-namespace
  name: rabbitmq-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
